c_compiler:
- gcc
c_compiler_version:
- '12'
cdt_name:
- cos7
cdt_arch:
- armv7l
channel_sources:
- conda-forge
channel_targets:
- conda-forge main
cxx_compiler:
- gxx
cxx_compiler_version:
- '12'
docker_image:
- quay.io/condaforge/linux-anvil-cos7-x86_64
ffmpeg:
- '5.1.2'
freetype:
- '2.12.1'
glib:
- '2.76.2'
harfbuzz:
- '7.2.0'
hdf5:
- 1.14.0
jasper:
- '4'
libcblas:
- 3.10.* *netlib
libjpeg_turbo:
- 2.1.5.1
liblapack:
- 3.10.* *netlib
liblapacke:
- 3.10.* *netlib
libpng:
- '1.6.39'
libprotobuf:
- '3.21.12'
libtiff:
- '4.5.0'
libwebp:
- '1.3.0'
numpy:
- '1.24'
- '1.24'
- '1.24'
- '1.24'
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
python:
- 3.11.* *_cpython
- 3.10.* *_cpython
- 3.9.* *_cpython
- 3.8.* *_cpython
qt_main:
- '5.15'
target_platform:
- linux-armv7l
zip_keys:
- - c_compiler_version
  - cxx_compiler_version
- - python
  - numpy
zlib:
- '1.2.13'
