name: Build Conda packages with conda-build

on: push

jobs:
  build-linux:
    strategy:
      fail-fast: true
      matrix:
        include:
        - name: linux_armv7l_config_py310_ffmpeg6.yaml
          config_file: .ci_support/linux_armv7l_config_py310_ffmpeg6.yaml
        - name: linux_armv7l_config_py310_ffmpeg7.yaml
          config_file: .ci_support/linux_armv7l_config_py310_ffmpeg7.yaml
        - name: linux_armv7l_config_py311_ffmpeg6.yaml
          config_file: .ci_support/linux_armv7l_config_py311_ffmpeg6.yaml
        - name: linux_armv7l_config_py311_ffmpeg7.yaml
          config_file: .ci_support/linux_armv7l_config_py311_ffmpeg7.yaml
        - name: linux_armv7l_config_py312_ffmpeg6.yaml
          config_file: .ci_support/linux_armv7l_config_py312_ffmpeg6.yaml
        - name: linux_armv7l_config_py312_ffmpeg7.yaml
          config_file: .ci_support/linux_armv7l_config_py312_ffmpeg7.yaml
        - name: linux_armv7l_config_py38_ffmpeg6.yaml
          config_file: .ci_support/linux_armv7l_config_py38_ffmpeg6.yaml
        - name: linux_armv7l_config_py38_ffmpeg7.yaml
          config_file: .ci_support/linux_armv7l_config_py38_ffmpeg7.yaml
        - name: linux_armv7l_config_py39_ffmpeg6.yaml
          config_file: .ci_support/linux_armv7l_config_py39_ffmpeg6.yaml
        - name: linux_armv7l_config_py39_ffmpeg7.yaml
          config_file: .ci_support/linux_armv7l_config_py39_ffmpeg7.yaml

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker info
      run: |
        docker info

    - name: Configure qemu
      run: |
        docker run --rm --privileged multiarch/qemu-user-static:register --reset -c yes

    - name: Build using docker
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN  }}
        CONFIG_FILE: ${{ matrix.config_file }}
      run: |
        pwd
        FEEDSTOCK_ROOT=$(pwd)
        docker run  \
           -v "${FEEDSTOCK_ROOT}":/home/conda/feedstock_root \
           -e ANACONDA_API_TOKEN \
           -e CONFIG_FILE \
           e8035669/linux-anvil-armv7l \
           bash /home/conda/feedstock_root/.scripts/run_armv7l_build.sh

